site_name: "FIWARE Big Bang"
site_description: FIWARE Big Bang (Let's FIWARE)

nav:
  - 'Home':
    - 'Index': index.md
    - 'Installation':
      - 'Installation': installation/index.md
      - 'Keyrock': installation/keyrock.md
      - 'Orion': installation/orion.md
      - 'Orion-LD': installation/orion-ld.md
      - 'Cygnus': installation/cygnus.md
      - 'Comet': installation/comet.md
      - 'Perseo': installation/perseo.md
      - 'QuantumLeap': installation/quantumleap.md
      - 'Draco': installation/draco.md
      - 'IoT Agent for UL': installation/iotagent-ul.md
      - 'IoT Agent for JSON': installation/iotagent-json.md
      - 'WireCloud': installation/wirecloud.md
      - 'Regproxy': installation/regproxy.md
      - 'Queryproxy': installation/queryproxy.md
      - 'Node-RED': installation/node-red.md
      - 'Grafana': installation/grafana.md
      - 'Zeppelin': installation/zeppelin.md
      - 'Certbot': installation/certbot.md
      - 'Firewall': installation/firewall.md
      - 'Multi-server': installation/multi_server.md
      - 'Expose ports': installation/expose-ports.md
    - 'After installation': after-installation.md
    - 'System Administration': system_administration.md
    - 'NGSI Go': ngsi-go.md
    - 'Get token': get_token.md
    - 'Examples':
      - 'Keyrock': examples/keyrock.md
      - 'Orion': examples/orion.md
      - 'Orion-LD': examples/orion-ld.md
      - 'Cygnus': examples/cygnus.md
      - 'Comet': examples/comet.md
      - 'Perseo': examples/perseo.md
      - 'QuantumLeap': examples/quantumleap.md
      - 'Draco': examples/draco.md
      - 'IoT Agent for UL': examples/iotagent-ul.md
      - 'IoT Agent for JSON': examples/iotagent-json.md
      - 'WireCloud': examples/wirecloud.md
      - 'Node-RED': examples/node-red.md
      - 'Grafana': examples/grafana.md
      - 'Zeppelin': examples/zeppelin.md
    - 'Troubleshooting': troubleshooting.md
