version: "3"
services:
  keyrock:
    image: ${IMAGE_KEYROCK}
    depends_on:
    # __KEYROCK_DEPENDS_ON__
    environment:
      - IDM_HOST=${IDM_HOST}
      - IDM_PORT=3000
      - IDM_DB_DIALECT=${IDM_DB_DIALECT}
      - IDM_DB_HOST=${IDM_DB_HOST}
      - IDM_DB_PORT=${IDM_DB_PORT}
      - IDM_DB_NAME=${IDM_DB_NAME}
      - IDM_DB_USER=${IDM_DB_USER}
      - IDM_DB_PASS=${IDM_DB_PASS}
      - IDM_ADMIN_UID=${IDM_ADMIN_UID}
      - IDM_ADMIN_USER=${IDM_ADMIN_USER}
      - IDM_ADMIN_EMAIL=${IDM_ADMIN_EMAIL}
      - IDM_ADMIN_PASS=${IDM_ADMIN_PASS}
      - IDM_SESSION_SECRET=${IDM_SESSION_SECRET}
      - IDM_ENCRYPTION_KEY=${IDM_ENCRYPTION_KEY}
      - IDM_DEBUG=${IDM_DEBUG}
    # __KEYROCK_ENVIRONMENT__
    volumes:
    # __KEYROCK_VOLUMES__
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[keyrock]"
